name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify
      - name: Copy artifact
        run: mkdir staging && cp target/*.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Building-Info
          path: staging
      - name: Generate javadoc
        run: mvn javadoc:javadoc
      - name: Upload javadoc
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: target/site/apidocs
